apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-spin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasm-spin
  template:
    metadata:
      labels:
        app: wasm-spin
    spec:
      runtimeClassName: wasmtime
      containers:
      - name: testwasm
        image: ghcr.io/mossaka/spinkitchensink:latest
        command: ["/"]